# See all options online:
#   https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

hide_parse_errors = false
unstable_features = true
edition = "2018"

# You can take my spaces from my cold, dead hands
hard_tabs = false
tab_spaces = 4
blank_lines_upper_bound = 2
normalize_doc_attributes = true

trailing_comma = "Vertical"
indent_style = "Block"
use_small_heuristics = "Default"

binop_separator = "Front"
combine_control_expr = true

# Let comments be a little wider
wrap_comments = true
max_width = 80
comment_width = 80
format_strings = true

brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

fn_args_density = "Tall"

empty_item_single_line = true
fn_single_line = false
where_single_line = false

enum_discrim_align_threshold = 40
struct_field_align_threshold = 40

struct_lit_single_line = true

# There is zero different between
#       extern { }
# and
#       extern "C" { }
# So remove the abiguity.
force_explicit_abi = true

format_macro_matchers = true
format_macro_bodies = false

imports_indent = "Block"
imports_layout = "Vertical"

match_block_trailing_comma = true
match_arm_blocks = true

# I like expressing meaning by how I group these
# e.g. I use #[derive(Copy, Clone, Debug)] by "default",
# so I want that as a single group.
merge_imports = false
merge_derives = false

force_multiline_blocks = true

normalize_comments = true
remove_nested_parens = true

# I'm already doing this manually, so definitely turn on!
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

space_before_colon = false
space_after_colon = true
spaces_around_ranges = false

trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true

# I'd be interested in the opposite of this:
# convert foo().bar()? into try!(foo().bar())
use_try_shorthand = true

format_doc_comments = true
overflow_delimited_expr = true

# These look useful when TODOs and FIXMEs have real ticket/issue numbers
# report_todo = "Unnumbered"
# report_fixme = "Unnumbered"

# Also useful for work:
# license_template_path = "./SOURCE_LICENSE_TEMPLATE.txt"
