// Copied over manually because I want the values in hex.
pub const GL_DEPTH_BUFFER_BIT: u32 = 0x00000100;
pub const GL_COLOR_BUFFER_BIT: u32 = 0x00004000;

// automatically generated by rust-bindgen

pub type GLenum = libc::c_uint;
pub type GLbitfield = libc::c_uint;
pub type GLint = libc::c_int;
pub type GLuint = libc::c_uint;
pub type GLsizei = libc::c_int;
pub type GLfloat = f32;
pub type GLdouble = f64;
pub type GLchar = libc::c_char;
pub type PFNGLCLEARPROC = unsafe extern "C" fn(mask: GLbitfield);
pub type PFNGLCLEARCOLORPROC = unsafe extern "C" fn(
    red: GLfloat,
    green: GLfloat,
    blue: GLfloat,
    alpha: GLfloat,
);
pub type PFNGLCLEARDEPTHPROC = unsafe extern "C" fn(depth: GLdouble);
pub type PFNGLATTACHSHADERPROC =
    unsafe extern "C" fn(program: GLuint, shader: GLuint);
pub type PFNGLCOMPILESHADERPROC = unsafe extern "C" fn(shader: GLuint);
pub type PFNGLCREATEPROGRAMPROC = unsafe extern "C" fn() -> GLuint;
pub type PFNGLCREATESHADERPROC = unsafe extern "C" fn(type_: GLenum) -> GLuint;
pub type PFNGLLINKPROGRAMPROC = unsafe extern "C" fn(program: GLuint);
pub type PFNGLSHADERSOURCEPROC = unsafe extern "C" fn(
    shader: GLuint,
    count: GLsizei,
    string: *const *const GLchar,
    length: *const GLint,
);
pub type PFNGLUSEPROGRAMPROC = unsafe extern "C" fn(program: GLuint);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GlFuncs {
    /// OpenGL32 module - must outlive the pointers in this struct.
    pub hOpenGL: u64,
    pub CreateShader: PFNGLCREATESHADERPROC,
    pub ShaderSource: PFNGLSHADERSOURCEPROC,
    pub CompileShader: PFNGLCOMPILESHADERPROC,
    pub AttachShader: PFNGLATTACHSHADERPROC,
    pub CreateProgram: PFNGLCREATEPROGRAMPROC,
    pub LinkProgram: PFNGLLINKPROGRAMPROC,
    pub UseProgram: PFNGLUSEPROGRAMPROC,
    pub ClearColor: PFNGLCLEARCOLORPROC,
    pub Clear: PFNGLCLEARPROC,
    pub ClearDepth: PFNGLCLEARDEPTHPROC,
}
extern "C" {
    /// Loads required OpenGL functions into pFns.
    ///
    /// Return value == 0  if all required functions are loaded.
    /// Return value <= -1 if someone went wrong - e.g. invalid arguments.
    /// Return value >=  1 if 1 or more functions failed to load.
    ///
    /// Functions are marked as required in the `GlFuncs` struct definition.
    pub fn ogl_load(pFns: *mut GlFuncs) -> libc::c_int;
}
